services:
  enviroment-server:
    build: infra/docker/ssh-server
    privileged: true
    environment:
      - GIT_NAME=Lorenzo Fornara
      - GIT_EMAIL=fw1987@gmail.com
    entrypoint: /usr/bin/entrypoint.sh
    container_name: enviroment-server
    hostname: "${HOSTNAME}->env"
    restart: always
    mem_limit: 512m
    ports:
      - 2222:22
    volumes:
      - home:/home
volumes:

  home:
    driver: local
