services:
  enviroment-server:
    build: infra/docker/ssh-server
    privileged: true
    entrypoint: /bin/bash -c "/usr/sbin/sshd -D -f /etc/ssh/sshd_config & dockerd"
    container_name: enviroment-server
    hostname: enviroment
    restart: always
    ports:
      - 2222:22
