services:
  enviroment-server:
    build: infra/docker/ssh-server
    privileged: true
    entrypoint: /bin/bash -c "/usr/sbin/sshd -D -f /etc/ssh/sshd_config & chown -R user:user /home/user/.ssh & dockerd"
    container_name: enviroment-server
    hostname: "${HOSTNAME}->env"
    restart: always
    ports:
      - 2222:22
    volumes:
      - ssh:/home/user/.ssh
      - home:/home
volumes:
  ssh:
    driver: local

  home:
    driver: local
    
    
