services:
  enviroment-server:
    build: infra/docker/ssh-server
    privileged: true
    entrypoint: /bin/bash -c "/usr/sbin/sshd -D -f /etc/ssh/sshd_config & dockerd"
    container_name: enviroment-server
    hostname: "${HOSTNAME}->env"
    restart: always
    ports:
      - 2222:22
    volumes:
      - ssh:/home/h4shell/.ssh

volumes:
  ssh:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/h4shell/
